# Generated by Django 6.0.5 on 2026-08-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0043_alter_birthdayrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdayrecord',
            name='birth_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
