# Generated by Django 6.0.5 on 2026-08-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0044_birthdayrecord_birth_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdayrecord',
            name='gender',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
