# Generated by Django 5.1.1 on 2026-05-19 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRecognitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_url', models.URLField(max_length=500, verbose_name='采集图片URL')),
                ('matched', models.BooleanField(default=False, verbose_name='是否匹配')),
                ('confidence', models.FloatField(default=0.0, verbose_name='相似度')),
                ('message', models.CharField(blank=True, max_length=200, verbose_name='结果消息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_recognition_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '人脸识别日志',
                'verbose_name_plural': '人脸识别日志',
                'db_table': 'tb_face_recognition_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
