version: "3"

volumes:
  db_vol:
  redis_vol:
  media_vol:

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge
  redis_network:
    driver: bridge

services:
  redis:
    image: redis:latest
    command: redis-server /etc/redis/redis.conf
    networks:
      - redis_network
    volumes:
      - redis_vol:/data
      - ./compose/redis/redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
    restart: always

  db:
    image: mysql:latest
    env_file:
      - kdx-be/.env
    networks:
      - db_network
    volumes:
      - db_vol:/var/lib/mysql:rw
      - ./compose/mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ./compose/mysql/init:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    restart: always

  web:
    build: kdx-be
    expose:
      - "8000"
    volumes:
      - ./kdx-be:/home/kdx-be
      - media_vol:/home/kdx-be/media
      - ./compose/uwsgi:/tmp
    networks:
      - nginx_network
      - db_network
      - redis_network
    depends_on:
      - db
      - redis
    restart: always
    tty: true
    stdin_open: true
    container_name: kdx-be

  kdx_ws:
    build:
      context: .
      dockerfile: kdx-ws-be/Dockerfile
    env_file:
      - kdx-ws-be/.env
    expose:
      - "8001"
    volumes:
      - ./kdx-ws-be:/app
    networks:
      - nginx_network
      - db_network
      - redis_network
    depends_on:
      - db
      - redis
    restart: always
    container_name: kdx-ws-be

  nginx:
    build: ./compose/nginx
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
    volumes:
      - ./compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./compose/nginx/ssl:/usr/share/nginx/ssl
      - ./compose/nginx/log:/var/log/nginx
      - ./kdx-fe/dist:/usr/share/nginx/html
      - media_vol:/usr/share/nginx/html/media
    networks:
      - nginx_network
    depends_on:
      - web
      - voice_ws
    restart: always
    container_name: kdx-nginx