# nginx配置文件
# compose/nginx/default.conf

upstream django {
    ip_hash;
    server web:8000; # Docker-compose web服务端口
}

upstream voice_ws {
    server voice_ws:8001;
}

upstream fastapi_app {
    server fastapi:8002;
}

server {
    listen       80;
    listen       [::]:80;
    server_name  _;

    charset utf-8;
    client_max_body_size 100M; # 限制用户上传文件大小

    location / {
        # First attempt to serve request as file, then
        # as directory, then fall back to displaying a 404.
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Support Vue Router history mode
        try_files $uri $uri/ /index.html;

        # Disable cache for index.html to ensure users always get the latest version
        if ($request_filename ~* ^.*?.(html|htm)$) {
            add_header Cache-Control "private, no-store, no-cache, must-revalidate, proxy-revalidate";
        }
    }


    location /prod-api/media {
         alias /usr/share/nginx/html/media;
    }

    location /prod-api/ws/ {
        proxy_pass http://voice_ws/ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 3600;
        proxy_send_timeout 3600;
    }

    location /prod-ai/ {
        proxy_pass http://fastapi_app/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect off;
        proxy_set_header X-Real-IP  $remote_addr;
    }

    location /prod-ai/ws/ {
        proxy_pass http://fastapi_app/ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 3600;
        proxy_send_timeout 3600;
    }

    location /prod-api/ {
        # method1 use uwsgi_pass
        #         include /etc/nginx/uwsgi_params;
        #         uwsgi_pass django;
        #         uwsgi_read_timeout 600;
        #         uwsgi_connect_timeout 600;
        #         uwsgi_send_timeout 600;

        # method2 use proxy_pass
        proxy_pass http://web:8000/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect off;
        proxy_set_header X-Real-IP  $remote_addr;
    }

    location /milvus {
        proxy_pass http://127.0.0.1:9091/webui;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect off;
        proxy_set_header X-Real-IP  $remote_addr;
    }


    # Load configuration files for the default server block.

    error_page 404 /404.html;
        location = /40x.html {
    }

    error_page 500 502 503 504 /50x.html;
        location = /50x.html {
    }
}

